services:
  meme-bot:
    build: .
    container_name: meme-bot
    restart: unless-stopped
    env_file:
      - ./prod.env
    environment:
      IS_DOCKERIZED: "true"
    volumes:
      - ./data/cookies.txt:/app/cookies.txt
      - ./data/bot.db:/app/data
    working_dir: /app
